### ISSUE TITLE
Add all available actions to Menus

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#10]
The 'h' hotkey to show shortcuts will work up to a point, but will likely run out of screen real-estate as the feature list grows. 

It would also be very useful to have available actions, visible in the menu (optionally in addition to the 'help' overlay). This is where most users look to find out available actions, and so would ease adoption. With MoliView, you need to remember about the 'h' shortcut ... as if you're dragging an image onto the icon, the welcome text doesn't show.

Additionally, by using standard menus, users would be able to configure their own Keyboards Shortcuts using the standard macOS settings.

**Comment by phaibin** [comment]
Yes, I agree. More and more keys have been added since the first version. A setting page is urgent now.

**Comment by phaibin** [comment]
Fixed in 1.7.0.
