### ISSUE TITLE
Configurable shortcuts

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#14]
Very low priority (as provided actions are represented in the menus, using the macOS systems settings you can remap the shortcuts as you see fit)...

... but it would be a nice-to-have to be able to configure which shortcut keys you wanted for an action, within the app.

**Comment by phaibin** [comment]
Yes, I'm working on it.

**Comment by phaibin** [comment]
Finally, I got the shortcuts config working.😂

**Comment by mcackay** [comment]
Wow. very nice shortcuts implementation :)

**Comment by newkind** [comment]
Wow! It looks great, you even have profiles! Thank you so much for that! I'm soooo happy that we finally are getting proper Xee replacement :)

One thing - I cannot change/set any new shortcuts. I can only select profile and view existing ones but when I try to add a new one or change existing - nothing happens, I just hear the beep sound.

**Comment by phaibin** [comment]
OK. I will add a notice to clarify the operation.

Some shortcuts are reserved and used very often in the system like page up and page down. And for the most frequent operation: jump to the next one, space is a very neat key to use. So these keys are revered.

Multiple shortcuts per action is much more complex to design the UI and code. And I think most people won't need it. Besides, a menu can only be bound to one shortcut. So I guess one shortcut per action is enough.

**Comment by newkind** [comment]
Sure, makes sense. The current solution is definitely enough :)

**Comment by newkind** [comment]
This looks great now! The locks are super nice details that make it even more clear. Thanks!
