### ISSUE TITLE
'File already exists' message easy to miss

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#15]
Thank you for implementing the Copy-to and Move-to function!

Been using them the past few days, and have noticed that it can be easy to miss a failed-copy/move, as the style of the alert is so similar to the success one.

Suggest one or more of the following:
* Change the colour of the 'failure' overlay to red
* Playing a different sound for success and failure
* Increase the time the failure overlay remains on screen before fading out and block further image navigation until the error has faded; OR \
Failure overlays should persist until you navigate to another image ... and navigation should be temporarily blocked so you can't inadvertently skip past the error if quickly doing a copy-next-copy-next sequence, etc.

**Comment by phaibin** [comment]
Good advice. I will fix it.

**Comment by mcackay** [comment]
Thanks @phaibin.\
The persistent dialog makes it impossible to miss the error 😄 

I've raised a minor improvement suggestion: 
- #25
