### ISSUE TITLE
File access issues

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#16]
Having a weird error that I can't seem to debug, as it's a bit inconsistent.

Attached is a screen recording of a simple use-case showing one of the failure modalities -- it's re-prompting me for directory access, even though I've granted that.

https://github.com/user-attachments/assets/48bbd7d4-ee15-4745-9d70-b2e3b5bfb89a

I've got another scenario, where I CAN browse through a directory if I drop the folder icon onto MoliView in the dock (and it doesn't prompt me for directory access) ... but if I drop a file from the same directory into the app icon, it prompts me for directory access, displays an error 'the file cannot be opened' (and the grey 'welcome window'  is showing the top-left part of the high-resolution at 1:1 pixel zoom ), and when I click OK on the error the image displays ... but I then can't browse to adjacent images.

This is also manifesting when attempting to use the 'Copy to' function ... to a directory that was working 8 hours ago.

--

I've tried resetting macOS security settings:

> tccutil reset All com.phaibin.iView 

and granting Full Disk Access to the app, etc ... but no joy.

Happy to provide more debug information if you can tell me how to obtain it. 
Can't see anything obvious in Console logs.

**Comment by mcackay** [comment]
Oddly, after restarting my computer, this appears to have come right.

It re-prompted for folder access the first time I tried to use 'Copy to...' but is not prompting me subsequently.

If this reoccurs, I'm still happy to grab further debug if you can tell me how.

**Comment by mcackay** [comment]
So went AFK for an hour or so, with an image still open in MoliView, and when I tried to use the Copy-To function, it came up with the 'This file cannot be opened' message again.

Similarly, when I quit MoliView and tried to re-open the image I was previously browsing, it had the same error (as per original video above), and I couldn't navigate. If I dragged the **folder** on to the MoliView icon it _could_ browse.

So something weird going on. Let me know what info I can get you to help.

**Comment by mcackay** [comment]
Thanks for the explanation about the OS permissions approach. 

I might try to report a bug to Apple, if I can get it to reoccur. Ironically it hasn't since my last report, but I've been a bit more careful to quit MoliView when I'm going AFK, and sleeping the computer overnight.

--

Re: default app -- yeah, I hadn't considered doing that yet, as I've only been using MoliView for 2-3 weeks so far.

I use Preview a lot for my work PDFs & images, and like the fact that I can quit and re-open it, and any open documents load up automatically to where I left off. I reboot regularly (and unfortunately get a few OS crashes for various reason), and love the app resume functionality.

But I have an Automator Workflow setup to launch MoliView with a keyboard shortcut ... which makes it really easy for me to launch it when I need it.

**Comment by phaibin** [comment]
Hi Mark, I encountered this issue once today. The error message is "Failed to retrieve app-scope key". If you reopen the app the error will disappear.

It's related to the saving permission process. I searched for this message and got very few helpful information. 

My solution is to ignore this error, and the user can continue browsing the images in the folder. But the permission wasn't saved successfully. So next time he will still be prompted to give the permission. It's not perfect but that's all I can do. I'll check it again after updating to macOS 15. Maybe it's related to some operation system error and will be fixed in macOS 15.

**Comment by phaibin** [comment]
Please check if this is fixed in 1.10.0.

**Comment by mcackay** [comment]
No issues so far with file access, but I'll let you know if I encounter any issues in the future.

**Comment by phaibin** [comment]
OK. You can reopen this issue anytime you find it happens again.

**Comment by phaibin** [comment]
This problem is much more serious in macOS 15 than in 14. It keeps occurring and can only be fixed by restarting the computer. But in macOS 14, it won't happen again after reopening the app.

**Comment by mcackay** [comment]
> This problem is much more serious in macOS 15 than in 14. It keeps occurring and can only be fixed by restarting the computer. But in macOS 14, it won't happen again after reopening the app.

FYI, I've not personally had the issue again since 1.10.0 release.
I just updated this morning to macOS 15.1 beta 4 -- no issues so far there either.
