### ISSUE TITLE
'Copy To' folder management

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#17]
Adding a new folder to the 'Copy to' function, ended up pushing my existing folder down the list, and incrementing the shortcut key for all existing folders. I could not figure out a way to reorder the folder list.

* Enable drag reordering of the folders
* Add a folder to the bottom of the list by default, so existing shortcut keys are not renumbered

**Comment by phaibin** [comment]
I got it. I don't know if the dragging is easy to implement, but the second one is easy.

**Comment by mcackay** [comment]
Thanks @phaibin.\
Drag and drop working well!

P.S. Let me know if you ant me to close these issues once confirmed working, or if you prefer to close them out, and I'll just add a comment once tested at my end.

**Comment by phaibin** [comment]
@mcackay It's not a problem. You can just leave them open. I want to check your feedback and decide if it has been done.😁
