### ISSUE TITLE
Show copy/move target in overlay

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#18]
When you just use a shortcut key to initiate a copy - e.g. Cmd-4 -- you're using your memory of which number maps to which folder. 

It would be helpful to include the target folder in the overlay -- e.g. 

> **Copy Complete**
\<target folder name\>

Similarly, if possible, it would be great to be able to Cmd-Z / Undo to revert the copy/move, so you can quickly correct your target folder if you made an error.

**Comment by phaibin** [comment]
Yes, this is convenient. I'll check if this is possible.

**Comment by mcackay** [comment]
Seems to be present in 1.8.0. Thanks!

**Comment by phaibin** [comment]
I will open another issue to deal with the Undo / Redo action.
