### ISSUE TITLE
Copy to: Option to keep folder list open

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#20]
I often keep around 6-10 folders in the Copy list that I regularly copy/move images to, some of which are temporal for events/etc. While I generally remember which shortcut key maps to which folder, it can be helpful to be able to see that easily.

Xee provided the folder list in a sidebar -- which you could choose to show/hide by using Cmd-Shift-C ... or just use the shortcut key directly, if you had confidence in your memory :)

Infrequently accessed folders could then also still be quickly accessed, but clicking the 14th, 16th folder in the list/etc as you browsed.

Would love to see something like this, to aid in quickly finding the right target folder/shortcut. Could be a floating window that a user could drag and position where they wanted on screen ... or the slide-out drawer style that Xee had/etc.

**Comment by phaibin** [comment]
I don't like the way Xee shows the copy list. It will cause the image to keep moving in the window. Maybe I'll consider using the floating window.

**Comment by mcackay** [comment]
Thanks @phaibin.

Seems to be working, and can see that the window location is persisted in-session, which is great.

I'll create a separate ticket with some ideas that would further improve usability.

* #26
