### ISSUE TITLE
Directory looping enhancements

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#21]
Would it be possible to add:

* Preference to enable/disable directory looping
* Overlay message shown when reach beginning/end of directory and try to navigate further but can't
* Overlay message shown if looping enabled, and you are going back to the start of the directory

**Comment by phaibin** [comment]
Yes, this is reasonable.

**Comment by newkind** [comment]
@phaibin I think that the messages should be possible to be disabled. To be honest I personally don't like the popup window that appears when I reach the last image. Can this be a toggle in the settings please? :)

**Comment by mcackay** [comment]
@phaibin Thanks again for taking on this idea. The looping seems to be working well.

### Re: Looping Overlay

I can see overlays appearing when you reach the first and last image: "Last One! Will be back to the first one". 

And when you use the Home or End shortcuts, you see the overlay saying they're at the end, even though that was the user's intentional action.

Taking into account @newkind's feedback, I would suggest a few tweaks to reduce the frequency of the messages and make them more relevant:

* Show the overlay only when the loop transition occurs (e.g. from last to 1st image)
* Update wording to something like: "Looped back to beginning/end"

... that way, if someone has 'Loop Images' disabled, they'll never see the overlay.

I've also note that the overlay is only showing for as long as you have the first/final image is showing on screen. If you are quickly scanning the directory, it may only show up for a 100ms or so -- and I'm can be very easy to miss. Suggest:

* Persist the "Looped..." overlay onscreen for 1-3 seconds\
(even if the user changes image).

* Potentially shift the location of the 'Looping...' overlay to the top/bottom of the image, so it doesn't get in the way of 'action' overlays such as 'Copy To...'

**Comment by newkind** [comment]
These tweak suggestions seem nice @mcackay, however I just don't want these overlays at all - doesn't matter if the loop is enabled or disabled. For me they are distracting and unneeded, that's why I think you should be able to have a configuration option to enable or disable them entirely. 

If someone prefers to use them and has an usage for them - like you - they can enable them, if someone doesn't need them - just disable them in the settings. This makes everyone happy and allow them to set the Moli the way they want it :)

**Comment by phaibin** [comment]
@mcackay That's better. 

Actually I don't like the message either.😂 So I'll add a switch to this function and it will default to off. Sorry about that.

**Comment by phaibin** [comment]
@mcackay @newkind Please check if the prompt is OK.

**Comment by mcackay** [comment]
Working great for me thanks :)

**Comment by newkind** [comment]
Looks good, I love that its disabled by default :) Also I think that you did improve the design nicely for people who will use it. Awesome job!
