### ISSUE TITLE
Pre-caching of prev/next sequential and random images

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#22]
Maybe MoliView does this already -- but I wondered how easy it might be to implement preloading and caching of the previous/next sequential and prev/next random files?

I use a NAS at home, and sometimes there's a bit of obvious lag while trying to browse between files, due to the slow I/O. However the system is going to be idle for at least a few hundred milliseconds as you glance at an image, and react to trigger the command to browse to the next image/etc. 

Would it be possible to pre-cache the next images to avoid the subsequent fetch-delay?

**Comment by phaibin** [comment]
I haven't done this. I'll check if this is possible.

**Comment by mcackay** [comment]
It's hard to know exactly what the net render-time change is, but the way it's implemented does make using the arrow keys to quickly skim though a directory  feel more responsive. 

The screen is showing a grey placeholder, until the image is loaded and rendered -- but is actually navigating more quickly ... whereas the 1.7.0 seems to pause briefly, which was more noticeable on NAS storage.

So I guess I'd say for me, yes, this is working great -- and doesn't appear to have been any instability or memory issues observed so far.

Thank you very much, again!

**Comment by phaibin** [comment]
Yes, this image loading has been changed to an asynchronous way. You will not see the gray screen if the cache system works well. I have to say it didn't work as well as I expected. Maybe your NAS network is really slow.😂

**Comment by mcackay** [comment]
I was flicking through at a very fast pace, intentionally trying to push the preloading system -- and the images were on the larger size.

The async method works well though -- if you want to navigate forward a certain number of images, you no longer need to wait for each one to load -- and it feels more natural, IMHO.

What is it pre-caching out of curiosity?  e.g. current + 1 next sequential, 1 next previous, 1 next random, 1 prev random?

**Comment by phaibin** [comment]
For a good user experience, it's better to load +1, +2, -1, -2, +10, +11, -10, -11, +100, +101, -100, -101, first one, last one, random +1, random +2, random -1, random -2. But it adds up to 18 items. I have to cut it off to: +1, +2, -1, -2, +10, -10, +100, -100, first one, last one, random +1, random -1. For images that aren't very large, it's OK. But if the images are very large, the cache will not hold all of these items. And you'll experience grey blinks between navigations.
