### ISSUE TITLE
Natural sorting

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#23]
Could the directory browsing be changed, to support natural sorting - so the numbers are in sequence, and matching the finder behaviour?

Currently files are sorting in the order:
* ...1.jpg
* ...11.jpg
* ...12.jpg\
\<snip\>
* ...18.jpg
* ...19.jpg
* ...2.jpg
* ...20.jpg
* ...

**Comment by phaibin** [comment]
I didn't notice that. You have very sharp eyes.👍

**Comment by mcackay** [comment]
Working well in 1.8.0 :smile:
