### ISSUE TITLE
Crash when trying to 'Show in Finder'

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#24]
In 1.7.0 I'm getting a crash every time I try to 'Show in Finder' -- either via the menu or the "L" shortcut.
I'm pretty sure this was working fine in the previous version (or if it did crash, it was less frequent).

I've reported crash logs to Apple ... do you get access to these?
Or if not, let me know if there's any other info I can provide.

**Comment by phaibin** [comment]
I didn't have any problems with my macOS 14.6.1 and 15.0. Seems like I'd have to download a macOS 15.1 mirror to test it.

**Comment by mcackay** [comment]
If you're only testing against 15.0 that's fine -- my pain for testing a pre-pre-release. 

It's not a big issue, as it actually it shows the file in the Finder _then_ crashes ... so it's easy to reopen the file and continue browsing. 

Will keep you posted with let you know if it reoccurs with the next 15.1 beta.

**Comment by phaibin** [comment]
I finally caught this bug😂. It's my mistake.

**Comment by mcackay** [comment]
No longer occurring in 1.9.0 with macOS 15.1 beta 3 :smile:
