### ISSUE TITLE
Dismiss 'File exists' dialog with Escape or Enter.

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#25]
Most Copy To / Move to operations, unless you have a lot of folders configured, will likely be keyboard actions on the left hand side of your keyboard (i.e. Cmd-1, Cmd-2).

But when the 'File exists' dialog is on shown on screen, you have to switch hands to hit the enter key.

It would be helpful if you could use either the Enter or Escape key to do this.

**Comment by phaibin** [comment]
This is included in 1.10.0. Please test.

**Comment by mcackay** [comment]
Working well for me, thanks!
