### ISSUE TITLE
'Copy To' Window improvements

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#26]
To maximise UX, I'd suggest the following:

* Remember the window location (and size) between application restarts
* Let the shortcut (e.g. Cmd-Shift-C) both show **and hide** the folder list window.

It can also be a bit visually dominant if left open, so suggest:

* Allow re-sizing of the window (i.e. so you can make it small and narrow)
* Potentially change the style to a semi-transparent glass window (similar to the overlay) ... so that if you do end up leaving the window onscreen, but are browsing larger images ... you can still see the broad contents of them through the window).

**Comment by phaibin** [comment]
@mcackay 
I tried to change the size and position of the "Copy to" window. It sure can remember these settings after restart. I don't know why it doesn't work on your side.

For the semi-transparent style, do you mean like this?
![QQ20240912-223631](https://github.com/user-attachments/assets/3a399f75-35b3-4dbd-aa8c-337392481b82)

**Comment by mcackay** [comment]
Hi @phaibin - 

re: Transparency - yes, that's great.

re: Resize -- in 1.9.0 (running macOS 15.1 beta) I can't seem to trigger any resize handles at the edge of the window. 

Re: remember position: it remembers while the app is running, but when I restart the app (i.e. with a different image folder) the Copy window returns to the middle of the image (even if had off to the side prior to quit).

**Comment by phaibin** [comment]
For remember position: I have to add some special judgments for macOS 15.0. Please test if it works on your side.

**Comment by mcackay** [comment]
Yes, seems to be working nicely with macOS 15.1 beta. Thanks again!
