### ISSUE TITLE
Fade-out 'Copy complete' overlay more-quickly, after image change

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#29]
I have noticed that if you're quickly copying a bunch of photos in succession, that the 'Copy complete' overlay feels like it lingers over the next image for too long.

With the overlay in the centre of the screen, and the centre of most images often containing the key subject of the photo ... this forces you to pause, and wait for the overlay to fade and reveal the subject.

I'd suggest:
* If you use the Copy/Move shortcut - and _remain on the same image_ - then the 'Copy complete' overlay should remain onscreen for around the current amount time
* If you trigger a copy, and the copy is successful -- _and then navigate to the next image_ -- then the fade-duration should be  much quicker (like 1/2 to 1/3 current time).

Combined with the existing behaviour, where the 'copy error' dialog prevents you navigating forward if the copy failed ... this should give you good confidence to quickly copy a bunch of images, but without the overlay obscuring the next image in the sequence for too long.

Perhaps also move the overlay up to the top of the screen (similar to the 'Looped' overlay) ... if that still looks OK, to further remove visual distraction.

P.S. the new overlay content, with the target folder on the second line is working well. Very helpful to make sure you selected the right path.

**Comment by phaibin** [comment]
Realsed in 1.10.0.

**Comment by mcackay** [comment]
Working well, thanks
