### ISSUE TITLE
Odd fullscreen behaviours (with multiple images)

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#31]
I don't have clear debug steps, but have noticed a few things when trying to real with going into full-screen mode, with **multiple images open** in MoliView.

* I have multiple desktop spaces setup, which I switch between for work/personal/specific tasks/etc.
* MoliView is typically on the 3rd of 4th space.

With multiple images open, and using the 'F' fullscreen shortcut key -- I observed behaviour like:

* opening one image fullscreen _might_ have taken both images fullscreen at one point.
* another time, opening one image fullscreen moved at image to a new 'fullscreen space', and I could navigate back to the space Moliview was running on.  if I then tried to full-screen the 2nd image ... the new 'fullscreen face' had its imaged replaced with the new one. But I couldn't find out how to switch to the previously full-screen image. Alt-Tab didn't work, Alt-` (tilde) didn't work. I then browsed my spaces and found the FIRST macOS space in windowed mode (not the one MoliVIew was running had the original image on it). When I exited fullscreen on the 2nd image, it returned to windowed mode on the First space too.

I suspect it's probably easier for you to test this behaviour out yourself, and tweak the behaviour a bit first -- and then I can advise if there's any further issues I can observe or feedback.

My broad goals would be:
* When I fullscreen an image, a new 'space' is created
* This space could be re-used for subsequent images (or, if macOS allows it ... potentially could spawn additional spaces)
* Either only allow one image to be full-screened at a time OR allow Cmd-` (tilde) to allow you to swap between fullscreen images.
* When you exit a fullscreen image, it returns to the 'windowed' form **in the same space it was originally on**.

**Comment by phaibin** [comment]
The fullscreen behavior has been fixed. And the "cmd+`" shortcut is working under fullscreen now.

**Comment by mcackay** [comment]
That's working well, thanks -- kinda nice being able to open them up in separate spaces too.
