### ISSUE TITLE
Standard(?) macOS file management via title bar?

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#32]
It would be nice to have the standard file management options, available via the menu bar.

<img width="569" alt="Screenshot 2024-09-18 at 7 15 52 AM" src="https://github.com/user-attachments/assets/4339cade-17cb-4ebb-9617-5e3558465b3d">

This was very handy to be able to copy the filename of something, or to rename a file. 

Alternatively Xee I think a Cmd-Enter shortcut which brought up a rename window -- which does have advantages of enabling mouse-free access to file renaming.

**Comment by phaibin** [comment]
Can you tell me which app are you using to show this menu bar? I think the Xee way is much easier to implement.

**Comment by mcackay** [comment]
Hi @phaibin  - that was just Preview.app.  Most official Apple apps support this interaction. I had assumed it was part of the standard NSDocument (or whatever it is nowadays) implementation. 

Xee’s rename approach was good too though. 

Quick keyboard access to rename (and/or copy current filename) is the main goal.

**Comment by phaibin** [comment]
OK. I'll use the Xee way.

**Comment by phaibin** [comment]
Released in 1.12.0
