### ISSUE TITLE
Persistent Rotation

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#33]
I'd love to be able to (optionally) persist the rotation setting of an image.

Xee allowed you to Cmd-S / Save, and I'm pretty saved in a way that didn't recompress the image, just modified the metadata.

Occasionally you'll want to look at an image from a different perspective temporarily, but most of the time the reason to rotate is to correct an image that isn't rendering the right way up.

**Comment by phaibin** [comment]
Released in 1.11.0. By using Apple native API, this function only supports JPEG, PNG, PSD, TIFF, and HEIF files. For other types of files, the save menu will be disabled. But besides the "What's New" announcement, I can't find a proper place to put this description in the App.

**Comment by mcackay** [comment]
Thanks @phaibin. Overseas at moment so can't fully test until I get back, but thanks for implementing.

Could potentially show a dedicated announcement window or overlay message about this feature, the first time someone tries to rotate an image - e.g. "You can persistently save this image orientation for supported files..."   That would only show up when relevant, and if a one-time notification, would be relatively unintrusive.

**Comment by phaibin** [comment]
Good advice. Thank you!

**Comment by phaibin** [comment]
@mcackay Please check if this function works as you expected.
