### ISSUE TITLE
Shortcut labels intermittently not displaying on "Copy To" window

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#34]
The "⌘1" shortcuts/etc are not always showing in the 'Copy To' / 'Move To' window:

<img width="268" alt="Screenshot 2024-09-23 at 11 01 56 AM" src="https://github.com/user-attachments/assets/07fe2747-3eb3-4f80-956e-0e4d3a2918d9">

Restarting app and/or resizing window does not seem to make a difference, nor reordering/adding/removing a folder.  However it sometimes returns.

Will let you know if I can determine a way to reproduce.

**Comment by phaibin** [comment]
It's just because of the transparent background and not so clear to see.😂
![QQ20240924-084718](https://github.com/user-attachments/assets/5891efb5-c2e3-4af9-8b1a-a9ef62a4c761)

I'll try to adjust a little bit.

**Comment by mcackay** [comment]
Doh!  Thanks -- that makes sense. I must have had a higher-contrast image behind it when I saw it show up (... and then couldn't figure out why I couldn't reproduce it by quitting/etc)

Thanks!

**Comment by phaibin** [comment]
Released in 1.11.0.

**Comment by phaibin** [comment]
@mcackay Please check if this is OK for you.
