### ISSUE TITLE
'Copy to' window title does not change to 'Move to'

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#35]
While the 'Copy To' window is open, if you press the shortcut for 'Move to', nothing appears to happen.

Would expect the 'Copy To' window title to change to 'Move To' and the shortcut codes to update to the configured Move shortcuts.

**Comment by phaibin** [comment]
Now you need to focus the image first and then press "cmd+shift+M" to activate the "Move to" window. I will add this feature.

**Comment by phaibin** [comment]
Released in 1.11.0.

**Comment by phaibin** [comment]
@mcackay Please check if this is OK for you.
