### ISSUE TITLE
Crash while tying to Browse folder in Copy To/Move To window

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#36]
When right-clicking on a folder in the copy-to window, and choosing 'Browse images' -- MoliView immediately crashes.

Trying to isolate the cause, it appears it may be due to folder permissions -- if I remove and re-add the directory to the copy-list (and unfortunately I had also, at the same time, added the parent volume target folders to the 'Folder Access' preferences) .... it then works.

**Comment by phaibin** [comment]
Released in 1.12.0

**Comment by mcackay** [comment]
Seems to be working again, thanks.
