### ISSUE TITLE
Skip to next, if underlying file disappears

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#38]
Xee had a nice behaviour, where if you renamed the currently open file / deleted it / etc ... using the Finder ... then it would skip to the next file in the sequence.

MoliView seems to restart from the first file in the directory -- which makes it harder to continue your editing/file-management flow at the point you ere working on.

**Comment by phaibin** [comment]
Yes, this is a problem. I will fix it.

**Comment by phaibin** [comment]
Released in 1.12.0

**Comment by mcackay** [comment]
working well thanks.
