### ISSUE TITLE
GIFs animate on direct load, but not prev/next

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#39]
When opening a GIF directly in MoliView it animates as expected.
But if browse to next file then back again, the GIF is no longer animated.

It may also be useful to have a setting which lets you limit the number of animations loops for a GIF to a certain count -- e.g. once, 5, 20, infinite.

**Comment by phaibin** [comment]
Yes, it's a bug and I've fixed it. Thank you!

I don't understand why we should add a loop count setting.

**Comment by mcackay** [comment]
The loop count was just a suggestion. I can't recall which, but I've seen a couple of apps stop GIFs animating after a couple of iterations. But thinking about it, it is probably more useful for energy-saving/distraction reduction ... and less useful in an image viewer (!) 😄

**Comment by phaibin** [comment]
Released in 1.12.0
