### ISSUE TITLE
Config folder permissions - Jakub

### ISSUE THREAD

**Issue by phaibin** [phaibin/MoliView#4]
![j3WCN8IZNJjaAMfwmc6vKa42MyobP0bprwe1H8Dm](https://github.com/user-attachments/assets/95232806-2f46-4618-b1c0-1aa423b9dfaa)

**Comment by phaibin** [comment]
Unfortunately, sandboxed apps can't grant full disk access. I'd have to wait until a setting page is added to add folder permission config. So this will be considered later.

**Comment by newkind** [comment]
Sure, no problem. I'm glad that you are considering some basic settings page at all. Thanks!

**Comment by phaibin** [comment]
Sorry for the late, you can config folder permissions now.

**Comment by mcackay** [comment]
Thanks for working on improvements here. -- a shame macOS safety makes this so hard.

--

I notice that every directory I browse, is getting added into the folders list -- even though the parent directory has already been added?

i.e. if I have ```/Volumes/<share>``` added ...\ 
but then browse ```/Volumes/<share>/path/to/folder``` \
... then ```/Volumes/<share>/path/to/folder``` gets added too.

Is this required by the OS?  or is adding 
* ```/Volumes``` or 
* ```/Volumes/<share>```
... enough to allow all child paths to be accessed.

This list was already getting quite long, after I opened up several dozen folders in my testing.

**Comment by phaibin** [comment]
Yes, this is a problem. I will fix it soon.

**Comment by phaibin** [comment]
Fixed in 1.10.1.

**Comment by newkind** [comment]
Works great! Thanks!
