### ISSUE TITLE
Open With... functionality

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#40]
Xee had the option to the current image with another application -- Photoshop. It would be great to have similar functionality.

I wasn't always delighted with Xee's implementation - I couldn't figure out how to consistently manage the list of applications that you could open with ... it recognised on supported file types I think, but that meant configuring it to open a script which did some batch processing/etc wasn't easy to effect.

Ideally MoliView would implement:
* Ability to configure one or more apps which you can open the current image in
* Ability to specify the app(s) explicitly ... rather than filetype determination ... to enabled scripts/automator/etc actions
* Ability to configure a shortcut for each of these (or at least a default one ... and then can use the systems shortcuts to configure one for other items in the menu)

**Comment by mcackay** [comment]
Hi @phaibin - 

As you've proposed seems like a good addition.

It would be helpful ... at least for me 😄  ... to be able to:

* **Configure multiple 'open-with' apps** \
i.e. I use both Preview & Pixelmator as editors -- Preview for quick edits (i.e. brightness and cropping), but Pixelmator when something more involved is required. Maybe this could be handled simply by including the "Open with..." submenu (similar to Xee) so that you can open in a different application when desired (and a power user could use macOS settings panel to configure shortcuts on other items in that menu.

* **Support Automator Quick Actions** \
Another way to handle the power-user case, would be to use Automator actions. But either I'm doing something wrong here, or I can't figure out how to create a Quick Action that takes the current image as the input. I'm not sure if apps need to be configured explicitly to support Quick Actions?\
\
I'd like to be able to 'Run shell script' and pass in the image path as an argument, to trigger resizing, or open in a different app, etc.

**Comment by phaibin** [comment]
I'm a little confused with Automator Quick Action. I think a Quick Action is triggered in Finder and directly forwarded to an Editor, and MoliView won't be involved. Can you give me an example of what you want to do and what MoliView needs to do?

**Comment by mcackay** [comment]
Yeah, maybe I am misunderstanding what Quick Actions supports.

I have Quick Actions working in finder - but I have to keep using the "L" shortcut to open the local file, then the shortcut key to trigger the Quick Action. I was hoping there was a way to initiate this within MoliView.

Like in MoliView I can see the following at all times.

<img width="498" alt="image" src="https://github.com/user-attachments/assets/45f4de58-4696-4aaf-ac19-fb80b10a3d0a">

In Safari, when you have text selected (for example), other QuickActions appear:

<img width="608" alt="image" src="https://github.com/user-attachments/assets/7840cb13-3825-4389-8a7f-df222407eb36">

I was thinking that I could create a QuickAction that was MoliView specific, that would take the current image as the argument:

<img width="684" alt="image" src="https://github.com/user-attachments/assets/159d0144-cb4b-4da6-b05c-b693e567bbeb">

But this doesn't seem to work, and I can't find example of any other apps that have Quick Actions **that take input** in their Service List. But a QuickAction that takes no input is not helpful for my use-case.

Anyways, Not an area I have much experience with. Perhaps this is not possible.

The proposed "Open with..." or "Edit with..." functionality would be helpful in any case. Maybe I can build a stub app which I set as my default, which then gives me a choice of which app or script to subsequently run 😄

**Comment by phaibin** [comment]
I got what you mean. I need to do some research to find out how to archive this.

**Comment by mcackay** [comment]
Thanks @phaibin - it's would be nice-to-have type functionality, so just if you get the inkling.
A shortcut to open in a preferred editor would be useful to a much larger swath of users.

Really appreciate everything you're doing to evolve MoliView and create a powerful tool.

**Comment by phaibin** [comment]
Hi, I finally got the "Services" menu to work. It will show the same items as in "Finder". Please test it and feedback.

**Comment by mcackay** [comment]
Brilliant!  Yes, that seems to be working. It's picking up some existing Services I had configured.
And the new editor option is working well too.

Thank you!  🎉

**Comment by phaibin** [comment]
No worries. Actually, your advice is making MoliView better and I learned a lot.😁
