### ISSUE TITLE
Rename improvements

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#42]
* Please enable copy/paste for text in the field
* Standard text selection shortcuts -- Cmd-A, Home, End buttons
* Dialog width would ideally try to be wide-enough to show the full filename \
(perhaps up to 80% of the window width)

**Comment by phaibin** [comment]
OK.

**Comment by phaibin** [comment]
Edit shortcuts have been added. Home, End won't work. Use Cmd+Left/Right instead.

**Comment by mcackay** [comment]
Edit shortcuts working thanks.

Dialog width still a bit narrow when working with longer filenames, but not the end of the world.
<img width="377" alt="image" src="https://github.com/user-attachments/assets/96b843d4-92d5-45c7-80b7-ddfea8bb7955">

Thanks again.

**Comment by phaibin** [comment]
I didn't realize that your file has a so long name.😂
