### ISSUE TITLE
Option to keep zoom on next picture

### ISSUE THREAD

**Issue by Enor7** [phaibin/MoliView#43]
I'd greatly appreciate the ability to keep the zoom scale on the next image, but to move the navigation to the top of the image.
Thanks so much for a great app!

**Comment by phaibin** [comment]
Hi, I've added two options under the "View" menu. If you turn off the "Fit on Screen Automatically", the scale will be preserved.

![QQ20241025-112312](https://github.com/user-attachments/assets/03cdf6af-0197-4fce-b555-5925d4393685)
