### ISSUE TITLE
Option to keep running in the background

### ISSUE THREAD

**Issue by Eureka-0** [phaibin/MoliView#44]
When the last window is closed, the app quits. When I open a new image, a blank window first appears before the image loads. Could we have an option to keep Moliview running in the background even when all windows are closed?

**Comment by phaibin** [comment]
Sure. I'll add it in the next release.

**Comment by phaibin** [comment]
@Eureka-0 Hi, it has been added in release 1.15.0.
![QQ20241029-082526](https://github.com/user-attachments/assets/24e6b74c-e056-4d63-bd1a-1090cd71dddb)
