### ISSUE TITLE
Option to hide the info bar 

### ISSUE THREAD

**Issue by dokidil** [phaibin/MoliView#45]
Hi,

I couldn't find an option to hide the info bar at the bottom of the window. That would be great.
I would like to hide the file name bar on the top also, if possible.

Nevertheless, I like MoliView. So thank you for this :)

Oliver

**Comment by phaibin** [comment]
Hi,

Sorry for the late. I finally got this work. Hiding the title bar is so hard.😂

![QQ20241120-084007](https://github.com/user-attachments/assets/b97bceb2-69ae-484c-b0f5-f4931abbcaed)

**Comment by dokidil** [comment]
Wow...where can you find such a customer service?
Great work. Thank you very much 🙏
