### ISSUE TITLE
File Action Triggers Blank Screen and View Shift

### ISSUE THREAD

**Issue by eieidos** [phaibin/MoliView#47]
Hello,

Open windows momentarily go blank, and the view resets to the top-left corner whenever a file is moved or added across the directory. This disrupts the intended view.

Thanks.

**Comment by phaibin** [comment]
Hi,
I can't reproduce your issue. Could you give more details? Or a screen recording is better. Thank you!

**Comment by eieidos** [comment]
Try opening up an image and zoom in a couple times. Then add or remove a file from the same folder location as the opened image. This should cause the window to reorient the image to the top left corner. 

I'll try to make a video if you're not able to get the same results.

**Comment by eieidos** [comment]
Okay, it seems to be stable now. The windows are maintaining their size and zoomed-in portion of the image. To achieve this, I have only **(Fit on Screen Automatically)** enabled.

**Comment by phaibin** [comment]
OK. I get it. Thank you!

**Comment by phaibin** [comment]
Hi,
This issue has been fixed in 1.16.1. Please check it.
