### ISSUE TITLE
"#" not working as custom keyboard shortcut 

### ISSUE THREAD

**Issue by Flauchhaus** [phaibin/MoliView#48]
The "#" button cannot be used for custom keyboard shortcut. I tried to set it to go to a random image as the button is close to the cursor buttons on a german keyboard but once mapped the command isn't working, it just plays the default "cant use" sound of macOS on pressing.

**Comment by phaibin** [comment]
I've tried to add a fix. But since I don't have a German keyboard, I can't guarantee that the fix works. Please let me know if it works.

**Comment by Flauchhaus** [comment]
I can confirm that the issue is fixed,the "#" key can now be mapped. Thank you!
