### ISSUE TITLE
Feature Request: Browse by date added or date modified

### ISSUE THREAD

**Issue by Flauchhaus** [phaibin/MoliView#49]
Thank you for creating MoliView!
Is there an option to browse by date added or date modified? Currently it seems to just browse by filename unless I am not seeing the option to switch.

**Comment by Flauchhaus** [comment]
Thank you for the extremely fast fix! It works great for individual folders now but when the "Include Images from Subfolders" option is turned on it and a folder containing subfolders that has images with various modified dates in it is opened in MoliView it displays the items from the first folder first instead of browsing through all images within any subfolders sorted by date.

**Comment by phaibin** [comment]
Yes, you're right. I will fix it.

**Comment by phaibin** [comment]
Has been fixed in 1.18.1.
