### ISSUE TITLE
Feature Request: Allow multiple custom buttons for one command

### ISSUE THREAD

**Issue by Flauchhaus** [phaibin/MoliView#50]
I woiuld like to map all cursor buttons for browsing, but I cannot seem to map one command to two custom buttons. My goal woukld be to map up/left as "previous image", and down/right as "next image". Thank you!

**Comment by phaibin** [comment]
Adding two shortcuts for one command is much more complicated. I intend to keep the shortcuts simple and easy to use. Sorry about that.

**Comment by Flauchhaus** [comment]
I understand, no worries I will learn the new behaviour.
