### ISSUE TITLE
Change status bar style when using dark mode - Jakub

### ISSUE THREAD

**Issue by phaibin** [phaibin/MoliView#6]
![B7q6Soba7bZC8EH2ySuGRATT9eYCl78N7vCLzqZk](https://github.com/user-attachments/assets/2f7e0b93-d3fd-43f4-b13f-9a848e567b3a)

**Comment by newkind** [comment]
Just to add to this issue - looks like it's the same background color as for the exif data. That one might need to get updated too.

![CleanShot 2024-08-17 at 09 30 52@2x](https://github.com/user-attachments/assets/c5680df4-aaf0-4520-8f86-d71e25f25c5b)

**Comment by phaibin** [comment]
You're right. Thank you!

**Comment by phaibin** [comment]
Fixed in 1.6.0
