### ISSUE TITLE
Toggle image panning using keyboard arrows - Jakub

### ISSUE THREAD

**Issue by newkind** [phaibin/MoliView#7]
Please consider adding a toggle/setting that would allow you to enable image paning using keyboard arrows just like in Xee. 
Even if it would be only just for the up/down arrows ie. when you are reading comic books and you enlarge the image you can use up/down arrows to scroll from top of the image to the bottom without touching the mouse.

If it would be only for the up/down arrow that would be enough for me, but if you would like to also enable it for left/right, then the hotkey to go to previous image could change to `cmd + ←` when keyboard paning is enabled.

If you still think its not a good idea, feel free to close this issue, but I still think its worth having a toggle in the app settings.

**Comment by phaibin** [comment]
Yes, you're right. Keyboard panning is necessary. I'll add it back if possible.

**Comment by phaibin** [comment]
Fixed in 1.6.0.

**Comment by newkind** [comment]
Awesome! Thank you!!! This is great!

Would you consider changing one thing here - to pan image use the arrows without the `cmd` modifier key and `cmd + arrow` to change the image to next/previous just like the original Xee did? I'm asking because there is a couple ways of changing the images already without the modifier keys like Space Bar, Page Up, Page Down but panning requires the modifier key. Ideally would be to make it like in the Xee.

That is would be my last missing piece :D If not, that's totally cool! Thank you for your hard work and sorry for bugging you ;) 

![CleanShot 2024-08-20 at 08 15 49](https://github.com/user-attachments/assets/5115d579-50f2-4f2c-81c6-569d13a02c4b)

![CleanShot 2024-08-20 at 08 19 28](https://github.com/user-attachments/assets/d09c7199-a237-4764-86bf-6ca20b18439b)

**Comment by phaibin** [comment]
I'm considering adding a settings page so users can customize these keys. But it may take some time.

**Comment by newkind** [comment]
That would totally work! Take all the time you need! I think you should increase the app price - its amazing :)
