### ISSUE TITLE
Wrong hotkey shown for rotate image in the help popup

### ISSUE THREAD

**Issue by newkind** [phaibin/MoliView#8]
![CleanShot 2024-08-17 at 15 01 03@2x](https://github.com/user-attachments/assets/204f3bf6-cbc0-4686-87bf-802bc3fab63c)

The rotate hotkey should be `cmd + R` as `R` is for random image.

You might want to add also `cmd + shift + R` to rotate counter clockwise.

**Comment by phaibin** [comment]
My bad.

**Comment by phaibin** [comment]
I want to explain why I've only added one key to rotate.
It's not very easy for me to choose which way to rotate, clockwise or counter. I have to think about maybe 5 seconds. Even if I choose the right way, I may use the wrong key. I think more functions will cause more confusion. If there is only one key, you don't have to think about it, just press 1, 2, or 3 times and you will get the right answer. Simple is beautiful.😁

**Comment by newkind** [comment]
I agree - simplicity is the key (!) but if you add another hotkey you're not forcing anyone to use both hotkeys - you can still just use `cmd + R` like right now (and even forget about the other one if you want to), but there definitely will be other people that will appreciate it as they are just used to rotating images everyday in both ways to fit their needs.

In worst case scenario you have to push the `cmd + R` 3 times to get to the right direction while in such case `cmd + shift + R` would be just only one press. 

Just think about this usage case - you are an architect and you are watching some plans using MoliView. You rotate it just once clockwise (90 deg) to see something better on the image (architect plans) and after that you want to get back to the original rotation - you need to rotate it again 3 times using `cmd + R` while it would require only 1 time to use `shift + cmd + R`.

If you still want to keep only 1 hotkey - that's totally cool :) This is not crucial for me at all, but having option to rotate image both ways kinda seems like a most basic functionality that every image viewer should have.

Anyways, once again for you hard work on the app!!!

**Comment by phaibin** [comment]
Yeah, you said it. Seems like I have to add it back.😂

**Comment by phaibin** [comment]
Fixed in 1.6.0.
