### ISSUE TITLE
Move/Copy to folder

### ISSUE THREAD

**Issue by mcackay** [phaibin/MoliView#9]
Xee had a capability to allow you to move or copy files to a set of pre-configured folders, which you could set up shortcuts for. This was very handy for casual photo management, such as copying a file you liked to your Wallpapers folder, etc. 

It made for a very efficient workflow - as it could be done while browsing images, using keyboard shortcuts. You didn't need to switch to using the mouse/trackpad, locate the relevant images on-disk, locate and open the target folder(s), and then drag and drop to the relevant files.

Key goals:
* **Ability to configure a list of one or more target folders**
Up to a reasonable limit of say 10, if needed, but unlimited if possible.

* **Configurable shortcut keys, to specify 'Copy current image to...' or 'Move current image to...'.** 
Xee from memory had Cmd-1 moved to first folder in the preset list, Ctrl-1 would move to 1st folder, etc ... though I changed this to Option-1 ... so it didn't conflict with the shortcut for macOS spaces).
In Xee, you could add unlimited folders .... but it didn't offer a shortcut beyond Command-9, though you could re-order the presets very easily in the side-panel by dragging them so that the folder you were working on was in the 'quick list' ... and you could just double-click on folders without a shortcut key, to copy them there.

* **Audible/visible confirmation** that the move was successful

* **Warning dialog if file exists at target location**, with option to Cancel, Overwrite ... and you could optionally add 'Keep Both'.

This may be beyond the scope of your goals for MoliView, but hopefully an enhancement that could be integrated at some point, to make it even more powerful.

(Currently I'm using MoliView to view images, as it works well and renders all images. But I have to switch to using Xee (even though not all images render properly) or the Finder to perform copy/move operations).

**Comment by phaibin** [comment]
Hi Mark, I've already added Copy/Move in 1.5.0. Although it may be a little different with Xee.

* If the file exists, there's only a warning instead of a confirm dialog.

I think it sure needs constantly adjusted. Please test it first and give some feedback.

**Comment by mcackay** [comment]
OMG. didn't realise it was already there!
You need a 'What's new' notification on update :)
